#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class AutoGenerateUpgradeAssets2D
{
    private const string RootFolder = "Assets/So/Upgrades/AutoGenerated";
    private const string PoolAssetName = "UpgradePool_Auto.asset";

    [MenuItem("Tools/그날이후/업그레이드 SO 자동 생성(슬롯 기반)")]
    public static void Generate()
    {
        var shooter = Object.FindFirstObjectByType<WeaponShooterSystem2D>();
        if (shooter == null)
        {
            Debug.LogError("[AutoGenerateUpgradeAssets2D] 씬에 WeaponShooterSystem2D가 없습니다.");
            return;
        }

        EnsureFolder("Assets/So");
        EnsureFolder("Assets/So/Upgrades");
        EnsureFolder(RootFolder);

        var createdCards = new List<WeaponUpgradeCardSO>(64);

        var soShooter = new SerializedObject(shooter);
        var pSlots = soShooter.FindProperty("slots");
        if (pSlots == null || !pSlots.isArray)
        {
            Debug.LogError("[AutoGenerateUpgradeAssets2D] WeaponShooterSystem2D에서 'slots' 배열을 찾지 못했습니다.");
            return;
        }

        DeleteAllAssetsInFolder(RootFolder);

        for (int i = 0; i < pSlots.arraySize; i++)
        {
            var elem = pSlots.GetArrayElementAtIndex(i);
            if (elem == null) continue;

            var pWeapon = elem.FindPropertyRelative("weapon");
            if (pWeapon == null || pWeapon.propertyType != SerializedPropertyType.ObjectReference) continue;

            Object weaponObj = pWeapon.objectReferenceValue;
            if (weaponObj == null) continue;

            // 핵심: 표시명/태그/프로토 포함 여부를 WeaponDefinitionSO에서 가져온다
            string weaponName = weaponObj.name;
            string tagsKr = "공통";
            string weaponId = null;

            if (weaponObj is WeaponDefinitionSO def)
            {
                if (!def.includeInPrototype) continue; // 최최종 기획안: 프로토 제외 대상은 생성에서 제외
                weaponName = def.GetDisplayName();
                tagsKr = string.IsNullOrWhiteSpace(def.tagsKr) ? "공통" : def.tagsKr;
                weaponId = def.weaponId;
            }

            // fallback: def 캐스팅 실패 시 기존 방식
            if (string.IsNullOrWhiteSpace(weaponId))
                weaponId = TryReadStringFieldAny(weaponObj, new[] { "weaponId", "id", "skillId", "weaponKey" });

            createdCards.Add(CreateCard_Enable(i, weaponName, weaponId, tagsKr));
            createdCards.Add(CreateCard_Damage(i, weaponName, weaponId, tagsKr, 2));
            createdCards.Add(CreateCard_CooldownMul(i, weaponName, weaponId, tagsKr, 0.92f));
            createdCards.Add(CreateCard_Range(i, weaponName, weaponId, tagsKr, 1.0f));
        }

        if (createdCards.Count == 0)
        {
            Debug.LogError("[AutoGenerateUpgradeAssets2D] 생성된 카드가 없습니다. slots에 weapon이 채워져 있는지, includeInPrototype이 true인지 확인하세요.");
            return;
        }

        var pool = CreateOrReplacePool(createdCards);

        var picker = Object.FindFirstObjectByType<LevelUpCardPicker>();
        if (picker != null)
        {
            var soPicker = new SerializedObject(picker);
            var pPool = soPicker.FindProperty("pool");
            if (pPool != null)
            {
                pPool.objectReferenceValue = pool;
                soPicker.ApplyModifiedProperties();
                EditorUtility.SetDirty(picker);
            }
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Selection.activeObject = pool;
        Debug.Log($"[AutoGenerateUpgradeAssets2D] 완료: 슬롯 기반 카드 {createdCards.Count}장, 풀 1개 생성/연결");
    }

    private static string TryReadStringFieldAny(Object obj, string[] fieldNames)
    {
        if (obj == null) return null;

        var so = new SerializedObject(obj);
        for (int i = 0; i < fieldNames.Length; i++)
        {
            var p = so.FindProperty(fieldNames[i]);
            if (p != null && p.propertyType == SerializedPropertyType.String)
                return p.stringValue;
        }
        return null;
    }

    private static WeaponUpgradeCardSO CreateCard_Enable(int slotIndex, string weaponName, string weaponId, string tagsKr)
    {
        var card = ScriptableObject.CreateInstance<WeaponUpgradeCardSO>();
        card.slotIndex = slotIndex;
        card.weaponNameKr = weaponName;
        card.weaponId = weaponId;

        card.type = WeaponUpgradeType.ToggleEnabled;
        card.value = UpgradeValue.Toggle(true);

        card.titleKr = $"{weaponName} 활성화";
        card.descKr = "해당 스킬을 사용할 수 있습니다.";
        card.tagsKr = tagsKr;

        SaveAsset(card, $"{RootFolder}/Card_Slot{slotIndex}_{SanitizeFileName(weaponName)}_Enable.asset");
        return card;
    }

    private static WeaponUpgradeCardSO CreateCard_Damage(int slotIndex, string weaponName, string weaponId, string tagsKr, int add)
    {
        var card = ScriptableObject.CreateInstance<WeaponUpgradeCardSO>();
        card.slotIndex = slotIndex;
        card.weaponNameKr = weaponName;
        card.weaponId = weaponId;

        card.type = WeaponUpgradeType.DamageAdd;
        card.value = UpgradeValue.AddInt(add);

        card.titleKr = $"{weaponName} 피해 +{add}";
        card.descKr = $"피해가 {add} 증가합니다.";
        card.tagsKr = tagsKr;

        SaveAsset(card, $"{RootFolder}/Card_Slot{slotIndex}_{SanitizeFileName(weaponName)}_DamageAdd_{add}.asset");
        return card;
    }

    private static WeaponUpgradeCardSO CreateCard_CooldownMul(int slotIndex, string weaponName, string weaponId, string tagsKr, float mul)
    {
        var card = ScriptableObject.CreateInstance<WeaponUpgradeCardSO>();
        card.slotIndex = slotIndex;
        card.weaponNameKr = weaponName;
        card.weaponId = weaponId;

        card.type = WeaponUpgradeType.CooldownMul;
        card.value = UpgradeValue.MulFloat(mul);

        float pctDown = (1f - mul) * 100f;
        card.titleKr = $"{weaponName} 발사 간격 {pctDown:0}% 감소";
        card.descKr = $"발사 간격이 {pctDown:0}% 감소합니다.";
        card.tagsKr = tagsKr;

        SaveAsset(card, $"{RootFolder}/Card_Slot{slotIndex}_{SanitizeFileName(weaponName)}_CooldownMul_{mul:0.00}.asset");
        return card;
    }

    private static WeaponUpgradeCardSO CreateCard_Range(int slotIndex, string weaponName, string weaponId, string tagsKr, float add)
    {
        var card = ScriptableObject.CreateInstance<WeaponUpgradeCardSO>();
        card.slotIndex = slotIndex;
        card.weaponNameKr = weaponName;
        card.weaponId = weaponId;

        card.type = WeaponUpgradeType.RangeAdd;
        card.value = UpgradeValue.AddFloat(add);

        card.titleKr = $"{weaponName} 사거리 +{add:0.#}";
        card.descKr = $"사거리가 {add:0.#} 증가합니다.";
        card.tagsKr = tagsKr;

        SaveAsset(card, $"{RootFolder}/Card_Slot{slotIndex}_{SanitizeFileName(weaponName)}_RangeAdd_{add:0.#}.asset");
        return card;
    }

    private static WeaponUpgradePoolSO CreateOrReplacePool(List<WeaponUpgradeCardSO> cards)
    {
        string path = $"{RootFolder}/{PoolAssetName}";
        AssetDatabase.DeleteAsset(path);

        var pool = ScriptableObject.CreateInstance<WeaponUpgradePoolSO>();
        pool.cards.Clear();
        pool.cards.AddRange(cards);

        SaveAsset(pool, path);
        return pool;
    }

    private static void SaveAsset(Object asset, string path)
    {
        AssetDatabase.CreateAsset(asset, path);
        EditorUtility.SetDirty(asset);
    }

    private static void EnsureFolder(string folderPath)
    {
        if (AssetDatabase.IsValidFolder(folderPath)) return;

        string parent = Path.GetDirectoryName(folderPath).Replace("\\", "/");
        string name = Path.GetFileName(folderPath);
        if (!AssetDatabase.IsValidFolder(parent))
            EnsureFolder(parent);

        AssetDatabase.CreateFolder(parent, name);
    }

    private static void DeleteAllAssetsInFolder(string folder)
    {
        string[] guids = AssetDatabase.FindAssets("", new[] { folder });
        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            if (path.EndsWith(".asset"))
                AssetDatabase.DeleteAsset(path);
        }
    }

    private static string SanitizeFileName(string s)
    {
        if (string.IsNullOrWhiteSpace(s)) return "Unnamed";

        var sb = new StringBuilder(s.Length);
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            if (char.IsLetterOrDigit(c) || c == '_' || c == '-')
                sb.Append(c);
            else
                sb.Append('_');
        }
        return sb.ToString();
    }
}
#endif
