#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class AutoGenerateSkillLevelTracks2D
{
    private const string TrackFolder = "Assets/So/SkillTracks/AutoGenerated";

    [MenuItem("Tools/그날이후/스킬 트랙 SO 자동 생성(1~8)")]
    public static void GenerateTracks()
    {
        var shooter = Object.FindFirstObjectByType<WeaponShooterSystem2D>();
        if (shooter == null)
        {
            Debug.LogError("[AutoGenerateSkillLevelTracks2D] 씬에 WeaponShooterSystem2D가 없습니다.");
            return;
        }

        EnsureFolder("Assets/So");
        EnsureFolder("Assets/So/SkillTracks");
        EnsureFolder(TrackFolder);

        // 기존 트랙 삭제(폴더 내 asset만)
        DeleteAllAssetsInFolder(TrackFolder);

        var slots = ReadSlots(shooter);
        int created = 0;

        for (int slotIndex = 0; slotIndex < slots.Count; slotIndex++)
        {
            var def = slots[slotIndex];
            if (def == null) continue;

            var track = ScriptableObject.CreateInstance<SkillLevelTrackSO>();
            track.weaponId = def.weaponId;
            track.displayNameKr = string.IsNullOrWhiteSpace(def.displayNameKr) ? def.name : def.displayNameKr;
            track.steps = BuildDefaultStepsFor(def);

            string path = $"{TrackFolder}/SkillTrack_{Sanitize(def.weaponId)}.asset";
            AssetDatabase.CreateAsset(track, path);
            EditorUtility.SetDirty(track);
            created++;
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log($"[AutoGenerateSkillLevelTracks2D] 완료: 트랙 {created}개 생성");
    }

    private static List<SkillLevelTrackSO.LevelStep> BuildDefaultStepsFor(WeaponDefinitionSO def)
    {
        // 이 기본 트랙은 “예시를 그대로 1~8로 만든 것”에 가깝다.
        // 스킬별로 주 성장축만 맞춰준다.

        var steps = new List<SkillLevelTrackSO.LevelStep>(8);

        // Lv1: 활성화
        steps.Add(Step(Upgrade(WeaponUpgradeType.ToggleEnabled, UpgradeValue.Toggle(true))));

        string wid = def.weaponId.ToLowerInvariant();

        // 회전검/부메랑/화살 멀티샷: 2레벨부터 투사체(또는 개수) +1
        bool isCountSkill =
            wid.Contains("rotate") || wid.Contains("sword") ||
            wid.Contains("boomerang") ||
            wid.Contains("arrow");

        // 총알: 2레벨부터 공격력 대폭
        bool isBullet =
            wid.Contains("bullet") || wid.Contains("gun") || wid.Contains("shot");

        // 수리검: 2레벨부터 튕김 +2, 그리고 피해 증가 교차
        bool isShuriken =
            wid.Contains("shuriken");

        // 다크오브: 분열 +2 교차 피해
        bool isDarkOrb =
            wid.Contains("darkorb") || wid.Contains("orb");

        // 호밍 미사일: 피해/연쇄(여기선 addSplit을 연쇄횟수로 대용)
        bool isHoming =
            wid.Contains("homing") || wid.Contains("missile");

        // 화살비: 여기서는 프로토에서 제외할 수도 있어서 기본은 피해/쿨타임만 넣고,
        // 틱 간격은 나중에 TickIntervalMul 타입 추가 시 바꾸는 걸 권장.
        bool isArrowRain =
            wid.Contains("arrowrain") || wid.Contains("rain");

        for (int lv = 2; lv <= 8; lv++)
        {
            if (isCountSkill)
            {
                // 회전검/부메랑/화살: 매 레벨 투사체 +1
                steps.Add(Step(Upgrade(WeaponUpgradeType.UpgradeStateAddShotCount, UpgradeValue.AddInt(1))));
                continue;
            }

            if (isBullet)
            {
                // 총알: 대폭 피해 증가 (예시로 +6씩)
                steps.Add(Step(Upgrade(WeaponUpgradeType.DamageAdd, UpgradeValue.AddInt(6))));
                continue;
            }

            if (isHoming)
            {
                // 호밍: 피해/연쇄 번갈아
                if (lv % 2 == 0)
                    steps.Add(Step(Upgrade(WeaponUpgradeType.DamageAdd, UpgradeValue.AddInt(4))));
                else
                    steps.Add(Step(Upgrade(WeaponUpgradeType.UpgradeStateAddSplit, UpgradeValue.AddInt(1))));
                continue;
            }

            if (isDarkOrb)
            {
                // 다크오브: 분열 +2 / 피해 교차
                if (lv % 2 == 0)
                    steps.Add(Step(Upgrade(WeaponUpgradeType.UpgradeStateAddSplit, UpgradeValue.AddInt(2))));
                else
                    steps.Add(Step(Upgrade(WeaponUpgradeType.DamageAdd, UpgradeValue.AddInt(3))));
                continue;
            }

            if (isShuriken)
            {
                // 수리검: 관통을 튕김으로 대용(+2), 피해 교차
                if (lv % 2 == 0)
                    steps.Add(Step(Upgrade(WeaponUpgradeType.UpgradeStateAddPierce, UpgradeValue.AddInt(2))));
                else
                    steps.Add(Step(Upgrade(WeaponUpgradeType.DamageAdd, UpgradeValue.AddInt(3))));
                continue;
            }

            if (isArrowRain)
            {
                // 화살비: 피해/쿨타임 번갈아(틱간격은 추후 타입 추가로 분리 권장)
                if (lv % 2 == 0)
                    steps.Add(Step(Upgrade(WeaponUpgradeType.DamageAdd, UpgradeValue.AddInt(4))));
                else
                    steps.Add(Step(Upgrade(WeaponUpgradeType.CooldownMul, UpgradeValue.MulFloat(0.92f))));
                continue;
            }

            // 기본: 피해/쿨타임 번갈아
            if (lv % 2 == 0)
                steps.Add(Step(Upgrade(WeaponUpgradeType.DamageAdd, UpgradeValue.AddInt(3))));
            else
                steps.Add(Step(Upgrade(WeaponUpgradeType.CooldownMul, UpgradeValue.MulFloat(0.92f))));
        }

        return steps;
    }

    private static SkillLevelTrackSO.LevelStep Step(params SkillLevelTrackSO.UpgradeDef[] upgrades)
    {
        var s = new SkillLevelTrackSO.LevelStep();
        s.upgrades = new List<SkillLevelTrackSO.UpgradeDef>(upgrades);
        return s;
    }

    private static SkillLevelTrackSO.UpgradeDef Upgrade(WeaponUpgradeType type, UpgradeValue value)
    {
        var u = new SkillLevelTrackSO.UpgradeDef();
        u.type = type;
        u.value = value;
        u.tagsKr = "공통";
        u.titleOverrideKr = "";
        return u;
    }

    private static List<WeaponDefinitionSO> ReadSlots(WeaponShooterSystem2D shooter)
    {
        // offerBuilder의 리더와 동일 방식(에디터용)
        var t = shooter.GetType();
        var slotsField = t.GetField("slots", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic);
        if (slotsField == null) return new List<WeaponDefinitionSO>();

        object slotsObj = slotsField.GetValue(shooter);
        if (!(slotsObj is System.Collections.IList list)) return new List<WeaponDefinitionSO>();

        System.Reflection.FieldInfo weaponField = null;
        var result = new List<WeaponDefinitionSO>(list.Count);

        for (int i = 0; i < list.Count; i++)
        {
            object elem = list[i];
            if (elem == null)
            {
                result.Add(null);
                continue;
            }

            if (weaponField == null)
            {
                weaponField = elem.GetType().GetField("weapon", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic);
                if (weaponField == null)
                {
                    result.Add(null);
                    continue;
                }
            }

            result.Add(weaponField.GetValue(elem) as WeaponDefinitionSO);
        }

        return result;
    }

    private static void EnsureFolder(string folderPath)
    {
        if (AssetDatabase.IsValidFolder(folderPath)) return;

        string parent = Path.GetDirectoryName(folderPath).Replace("\\", "/");
        string name = Path.GetFileName(folderPath);
        if (!AssetDatabase.IsValidFolder(parent))
            EnsureFolder(parent);

        AssetDatabase.CreateFolder(parent, name);
    }

    private static void DeleteAllAssetsInFolder(string folder)
    {
        string[] guids = AssetDatabase.FindAssets("", new[] { folder });
        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            if (path.EndsWith(".asset"))
                AssetDatabase.DeleteAsset(path);
        }
    }

    private static string Sanitize(string s)
    {
        if (string.IsNullOrWhiteSpace(s)) return "Unnamed";
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            if (!(char.IsLetterOrDigit(c) || c == '_' || c == '-'))
                s = s.Replace(c, '_');
        }
        return s;
    }
}
#endif
