#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class CommonSkillSOAutoBuilder
{
    private const string MenuRoot = "Tools/그날이후/CommonSkill/";
    private const string DefaultRootFolder = "Assets/SO_Weapon/CommonSkills";
    private const string GeneratedFolderName = "AutoGenerated";

    private struct SkillMeta
    {
        public string displayName;
        public int maxLevel;
        public int weight;
        public string[] prefabCandidates;
        public string[] iconCandidates;

        public SkillMeta(
            string displayName,
            int maxLevel,
            int weight,
            string[] prefabCandidates,
            string[] iconCandidates)
        {
            this.displayName = displayName;
            this.maxLevel = maxLevel;
            this.weight = weight;
            this.prefabCandidates = prefabCandidates;
            this.iconCandidates = iconCandidates;
        }
    }

    [MenuItem(MenuRoot + "1) 발시(Balsi) SO 생성/연동")]
    private static void CreateOrSyncBalsi()
    {
        Sync(new[] { CommonSkillKind.Balsi });
    }

    [MenuItem(MenuRoot + "2) 공통스킬 SO 전체 동기화(누락 생성/연동)")]
    private static void SyncAll()
    {
        Array values = Enum.GetValues(typeof(CommonSkillKind));
        var kinds = new CommonSkillKind[values.Length];
        for (int i = 0; i < values.Length; i++)
            kinds[i] = (CommonSkillKind)values.GetValue(i);

        Sync(kinds);
    }

    private static void Sync(CommonSkillKind[] kinds)
    {
        if (kinds == null || kinds.Length == 0) return;

        string commonSkillsFolder = FindOrCreateCommonSkillsFolder();
        string genFolder = EnsureFolder(commonSkillsFolder, GeneratedFolderName);

        var catalog = FindOrCreateAsset<CommonSkillCatalogSO>("CommonSkillCatalog", commonSkillsFolder);
        var pool = FindOrCreateAsset<CommonSkillCardPoolSO>("CommonSkillCardPool", commonSkillsFolder);

        if (catalog == null || pool == null)
        {
            EditorUtility.DisplayDialog("CommonSkill SO AutoBuilder", "Catalog 또는 Pool 생성/로딩 실패", "OK");
            return;
        }

        Undo.RecordObject(catalog, "Sync CommonSkillCatalog");
        Undo.RecordObject(pool, "Sync CommonSkillCardPool");

        if (catalog.cardPool == null)
        {
            catalog.cardPool = pool;
            EditorUtility.SetDirty(catalog);
        }

        catalog.skills.RemoveAll(x => x == null);
        pool.cards.RemoveAll(x => x == null || x.skill == null);

        // 기존 Config/Card 수집
        var allConfigs = LoadAllAssets<CommonSkillConfigSO>();
        var allCards = LoadAllAssets<CommonSkillCardSO>();

        var configByKind = new Dictionary<CommonSkillKind, CommonSkillConfigSO>(32);
        for (int i = 0; i < allConfigs.Count; i++)
        {
            var cfg = allConfigs[i];
            if (cfg == null) continue;
            if (!configByKind.ContainsKey(cfg.kind))
                configByKind.Add(cfg.kind, cfg);
        }

        int createdConfig = 0;
        int createdCard = 0;
        int addedToPool = 0;
        int fixedPrefabConfigRef = 0;

        for (int i = 0; i < kinds.Length; i++)
        {
            CommonSkillKind kind = kinds[i];
            SkillMeta meta = GetMeta(kind);

            // 1) Config 확보
            if (!configByKind.TryGetValue(kind, out var cfg) || cfg == null)
            {
                cfg = ScriptableObject.CreateInstance<CommonSkillConfigSO>();
                cfg.kind = kind;
                cfg.displayName = meta.displayName;
                cfg.maxLevel = Mathf.Max(1, meta.maxLevel);
                cfg.levels = BuildDefaultLevels(kind, cfg.maxLevel);

                cfg.icon = FindSprite(meta.iconCandidates);
                cfg.weaponPrefab = FindPrefab(meta.prefabCandidates);

                // weaponPrefab 유효성(필수: CommonSkillWeapon2D 존재)
                if (cfg.weaponPrefab != null && cfg.weaponPrefab.GetComponent<CommonSkillWeapon2D>() == null)
                    cfg.weaponPrefab = null;

                string cfgPath = ToUnityPath(Path.Combine(genFolder, $"CSkill_{kind}.asset"));
                cfgPath = AssetDatabase.GenerateUniqueAssetPath(cfgPath);
                AssetDatabase.CreateAsset(cfg, cfgPath);
                EditorUtility.SetDirty(cfg);

                configByKind[kind] = cfg;
                createdConfig++;
            }
            else
            {
                // 기존 에셋은 "비어있는 값만" 채움 (덮어쓰기 최소화)
                if (cfg.maxLevel < 1) cfg.maxLevel = 1;

                if (cfg.levels == null || cfg.levels.Length == 0)
                {
                    cfg.levels = BuildDefaultLevels(kind, Mathf.Max(1, cfg.maxLevel));
                    EditorUtility.SetDirty(cfg);
                }

                if (cfg.icon == null)
                {
                    var spr = FindSprite(meta.iconCandidates);
                    if (spr != null)
                    {
                        cfg.icon = spr;
                        EditorUtility.SetDirty(cfg);
                    }
                }

                if (cfg.weaponPrefab == null)
                {
                    var pf = FindPrefab(meta.prefabCandidates);
                    if (pf != null && pf.GetComponent<CommonSkillWeapon2D>() != null)
                    {
                        cfg.weaponPrefab = pf;
                        EditorUtility.SetDirty(cfg);
                    }
                }
            }

            // 2) Catalog 등록(무조건)
            if (cfg != null && !catalog.skills.Contains(cfg))
            {
                catalog.skills.Add(cfg);
                EditorUtility.SetDirty(catalog);
            }

            // 3) Card 확보
            var card = FindCardBySkill(allCards, cfg);
            if (card == null)
            {
                card = ScriptableObject.CreateInstance<CommonSkillCardSO>();
                card.skill = cfg;
                card.weight = Mathf.Max(1, meta.weight);

                string cardPath = ToUnityPath(Path.Combine(genFolder, $"CCard_{kind}.asset"));
                cardPath = AssetDatabase.GenerateUniqueAssetPath(cardPath);
                AssetDatabase.CreateAsset(card, cardPath);
                EditorUtility.SetDirty(card);

                allCards.Add(card);
                createdCard++;
            }
            else
            {
                if (card.skill == null)
                {
                    card.skill = cfg;
                    EditorUtility.SetDirty(card);
                }

                if (card.weight < 1)
                {
                    card.weight = Mathf.Max(1, meta.weight);
                    EditorUtility.SetDirty(card);
                }
            }

            // 4) Pool 등록(무조건 아님: 실행 가능한 스킬만 등록)
            bool runnable = (cfg != null && cfg.weaponPrefab != null && cfg.weaponPrefab.GetComponent<CommonSkillWeapon2D>() != null);
            if (runnable)
            {
                if (!pool.cards.Contains(card))
                {
                    pool.cards.Add(card);
                    EditorUtility.SetDirty(pool);
                    addedToPool++;
                }
            }
            else
            {
                // 잘못 등록된 “죽은 카드” 제거(뽑아도 아무 일도 안 생기는 상황 방지)
                if (pool.cards.Contains(card))
                {
                    pool.cards.Remove(card);
                    EditorUtility.SetDirty(pool);
                }
            }

            // 5) 프리팹 내부 CommonSkillWeapon2D.config 참조도 맞춰줌(편의)
            if (cfg != null && cfg.weaponPrefab != null)
            {
                if (TryFixPrefabConfigReference(cfg.weaponPrefab, cfg))
                    fixedPrefabConfigRef++;
            }
        }

        // 중복 제거(리스트 유지보수)
        RemoveDuplicates(catalog.skills);
        RemoveDuplicates(pool.cards);

        EditorUtility.SetDirty(catalog);
        EditorUtility.SetDirty(pool);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        EditorUtility.DisplayDialog(
            "CommonSkill SO AutoBuilder",
            $"완료\nConfig 생성: {createdConfig}\nCard 생성: {createdCard}\nPool 추가: {addedToPool}\n프리팹 config 참조 수정: {fixedPrefabConfigRef}\n생성 폴더: {genFolder}",
            "OK");
    }

    private static SkillMeta GetMeta(CommonSkillKind kind)
    {
        // 기본 가중치: 10
        // 메인 기본 스킬 가중치 +20% 느낌이면 12 정도가 안전한 시작값
        switch (kind)
        {
            case CommonSkillKind.Balsi:
                return new SkillMeta(
                    "발시",
                    8,
                    12,
                    new[] { "Weapon_Balsi", "BalsiWeapon", "Balsi" },
                    new[] { "Balsi" });

            case CommonSkillKind.ArrowShot:
                return new SkillMeta("기본 화살", 8, 10, new[] { "Weapon_Arrow", "ArrowShot", "Arrow" }, new[] { "Arrow" });

            case CommonSkillKind.DarkOrb:
                return new SkillMeta("암흑구", 8, 10, new[] { "Weapon_DarkOrb", "DarkOrb" }, new[] { "DarkOrb" });

            case CommonSkillKind.Shuriken:
                return new SkillMeta("수리검", 8, 10, new[] { "Weapon_Shuriken", "Shuriken" }, new[] { "Shuriken" });

            case CommonSkillKind.Boomerang:
                return new SkillMeta("부메랑", 8, 10, new[] { "Weapon_Boomerang", "Boomerang" }, new[] { "Boomerang" });

            case CommonSkillKind.HomingMissile:
                return new SkillMeta("유도 투사체", 8, 10, new[] { "Weapon_Homing", "Homing" }, new[] { "Homing" });

            case CommonSkillKind.PiercingBullet:
                return new SkillMeta("화승총", 8, 10, new[] { "Weapon_Musket", "Weapon_Bullet", "Bullet" }, new[] { "Bullet" });

            case CommonSkillKind.OrbitingBlade:
                return new SkillMeta("회전검", 8, 10, new[] { "Weapon_RotateSword", "OrbitSword", "RotateSword" }, new[] { "OrbitSword", "OrbitSword_Horizontal" });

            case CommonSkillKind.ArrowRain:
                // ArrowRain은 아직 CommonSkillWeapon2D 기반 프리팹이 없으면 자동으로 Pool에 안 들어가게 되어 있음
                return new SkillMeta("화살비", 8, 10, new[] { "Weapon_ArrowRain", "P_Weapon_ArrowRain", "ArrowRain" }, new[] { "RainArrow", "ArrowRain" });

            default:
                return new SkillMeta(kind.ToString(), 8, 10, new[] { kind.ToString() }, new[] { kind.ToString() });
        }
    }

    private static CommonSkillLevelParams[] BuildDefaultLevels(CommonSkillKind kind, int maxLevel)
    {
        maxLevel = Mathf.Max(1, maxLevel);
        var arr = new CommonSkillLevelParams[maxLevel];

        for (int i = 0; i < maxLevel; i++)
        {
            int lv = i + 1;
            var p = new CommonSkillLevelParams();

            // 공통 베이스
            p.cooldown = 0.55f;
            p.damage = 10 + (lv - 1) * 3;
            p.projectileCount = 1;
            p.projectileSpeed = 12f;
            p.lifeSeconds = 1.2f;

            // 스킬별 최소 조정(없으면 0 유지)
            switch (kind)
            {
                case CommonSkillKind.Balsi:
                    p.cooldown = 0.50f;
                    p.projectileCount = 1;
                    break;

                case CommonSkillKind.ArrowShot:
                    p.projectileCount = 1 + 2 * (lv - 1);
                    p.spreadAngleDeg = 8f;
                    break;

                case CommonSkillKind.Shuriken:
                    p.bounceCount = Mathf.Clamp(lv - 1, 0, 6);
                    break;

                case CommonSkillKind.HomingMissile:
                    p.chainCount = Mathf.Clamp(lv - 1, 0, 6);
                    p.turnSpeedDeg = 360f;
                    break;

                case CommonSkillKind.DarkOrb:
                    p.splitCount = Mathf.Clamp((lv - 1) / 2, 0, 4);
                    p.childSpeed = 10f;
                    p.explosionRadius = 1.5f;
                    break;

                case CommonSkillKind.OrbitingBlade:
                    p.projectileCount = 1 + (lv - 1) / 2;
                    p.hitInterval = 0.25f;
                    p.orbitRadius = 1.2f;
                    p.orbitAngularSpeed = 360f;
                    break;

                case CommonSkillKind.Boomerang:
                    p.returnSpeed = 18f;
                    break;

                case CommonSkillKind.PiercingBullet:
                    p.projectileSpeed = 18f;
                    break;
            }

            arr[i] = p;
        }

        return arr;
    }

    private static List<T> LoadAllAssets<T>() where T : UnityEngine.Object
    {
        var list = new List<T>(64);
        string[] guids = AssetDatabase.FindAssets($"t:{typeof(T).Name}");
        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            var a = AssetDatabase.LoadAssetAtPath<T>(path);
            if (a != null) list.Add(a);
        }
        return list;
    }

    private static T FindOrCreateAsset<T>(string assetName, string folder) where T : ScriptableObject
    {
        // 1) 같은 이름+타입이 있으면 우선 사용
        string[] guids = AssetDatabase.FindAssets($"{assetName} t:{typeof(T).Name}");
        for (int i = 0; i < guids.Length; i++)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[i]);
            var a = AssetDatabase.LoadAssetAtPath<T>(path);
            if (a != null && a.name == assetName)
                return a;
        }

        // 2) 타입이 1개라도 있으면 첫 번째 사용(프로젝트에 하나만 있다고 가정)
        guids = AssetDatabase.FindAssets($"t:{typeof(T).Name}");
        if (guids.Length > 0)
        {
            string path = AssetDatabase.GUIDToAssetPath(guids[0]);
            var a = AssetDatabase.LoadAssetAtPath<T>(path);
            if (a != null) return a;
        }

        // 3) 없으면 생성
        var created = ScriptableObject.CreateInstance<T>();
        string p = ToUnityPath(Path.Combine(folder, assetName + ".asset"));
        p = AssetDatabase.GenerateUniqueAssetPath(p);
        AssetDatabase.CreateAsset(created, p);
        EditorUtility.SetDirty(created);
        return created;
    }

    private static CommonSkillCardSO FindCardBySkill(List<CommonSkillCardSO> cards, CommonSkillConfigSO cfg)
    {
        if (cfg == null || cards == null) return null;
        for (int i = 0; i < cards.Count; i++)
        {
            var c = cards[i];
            if (c == null) continue;
            if (c.skill == cfg) return c;
        }
        return null;
    }

    private static Sprite FindSprite(string[] nameCandidates)
    {
        if (nameCandidates == null) return null;

        for (int i = 0; i < nameCandidates.Length; i++)
        {
            string key = nameCandidates[i];
            if (string.IsNullOrWhiteSpace(key)) continue;

            string[] guids = AssetDatabase.FindAssets($"{key} t:Sprite");
            for (int g = 0; g < guids.Length; g++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[g]);
                var spr = AssetDatabase.LoadAssetAtPath<Sprite>(path);
                if (spr != null) return spr;
            }
        }

        return null;
    }

    private static GameObject FindPrefab(string[] nameCandidates)
    {
        if (nameCandidates == null) return null;

        for (int i = 0; i < nameCandidates.Length; i++)
        {
            string key = nameCandidates[i];
            if (string.IsNullOrWhiteSpace(key)) continue;

            string[] guids = AssetDatabase.FindAssets($"{key} t:Prefab");
            for (int g = 0; g < guids.Length; g++)
            {
                string path = AssetDatabase.GUIDToAssetPath(guids[g]);
                var go = AssetDatabase.LoadAssetAtPath<GameObject>(path);
                if (go != null) return go;
            }
        }

        return null;
    }

    private static bool TryFixPrefabConfigReference(GameObject prefab, CommonSkillConfigSO cfg)
    {
        if (prefab == null || cfg == null) return false;

        string path = AssetDatabase.GetAssetPath(prefab);
        if (string.IsNullOrEmpty(path)) return false;

        GameObject root = PrefabUtility.LoadPrefabContents(path);
        if (root == null) return false;

        bool changed = false;

        try
        {
            var weapon = root.GetComponentInChildren<CommonSkillWeapon2D>(true);
            if (weapon == null) return false;

            var so = new SerializedObject(weapon);
            var prop = so.FindProperty("config");
            if (prop != null && prop.objectReferenceValue != cfg)
            {
                prop.objectReferenceValue = cfg;
                so.ApplyModifiedPropertiesWithoutUndo();
                changed = true;
            }

            if (changed)
                PrefabUtility.SaveAsPrefabAsset(root, path);
        }
        finally
        {
            PrefabUtility.UnloadPrefabContents(root);
        }

        return changed;
    }

    private static void RemoveDuplicates<T>(List<T> list) where T : class
    {
        if (list == null) return;
        var set = new HashSet<T>();
        for (int i = list.Count - 1; i >= 0; i--)
        {
            var v = list[i];
            if (v == null || set.Contains(v))
            {
                list.RemoveAt(i);
                continue;
            }
            set.Add(v);
        }
    }

    private static string FindOrCreateCommonSkillsFolder()
    {
        if (AssetDatabase.IsValidFolder(DefaultRootFolder))
            return DefaultRootFolder;

        // 프로젝트에서 CommonSkills 폴더를 찾아보고 있으면 그걸 사용
        string[] guids = AssetDatabase.FindAssets("CommonSkills t:Folder");
        for (int i = 0; i < guids.Length; i++)
        {
            string p = AssetDatabase.GUIDToAssetPath(guids[i]);
            if (p.EndsWith("/CommonSkills", StringComparison.Ordinal))
                return p;
        }

        // 없으면 기본 경로 생성
        string soWeapon = EnsureFolder("Assets", "SO_Weapon");
        return EnsureFolder(soWeapon, "CommonSkills");
    }

    private static string EnsureFolder(string parent, string child)
    {
        string path = $"{parent}/{child}";
        if (AssetDatabase.IsValidFolder(path))
            return path;

        AssetDatabase.CreateFolder(parent, child);
        return path;
    }

    private static string ToUnityPath(string path)
    {
        return path.Replace('\\', '/');
    }
}
#endif
