#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;

public static class WeaponSoAutoGenerator
{
    private const string OutputFolder = "Assets/SO/SO_Weapon/AutoGenerated";

    private static readonly string[] WeaponIds =
    {
        "Weapon_Arrow",
        "Weapon_DarkOrb",
        "Weapon_Shuriken",
        "Weapon_RotateSword",
        "Weapon_Boomerang",
        "Weapon_Homing",
        "Weapon_Musket",
        "Weapon_ArrowRain"
    };

    [MenuItem("Tools/Generate/Weapons/Create 8 WeaponDefinitionSO")]
    public static void CreateWeaponDefinitionSOs()
    {
        EnsureFolder(OutputFolder);

        int created = 0;

        for (int i = 0; i < WeaponIds.Length; i++)
        {
            string id = WeaponIds[i];
            string assetPath = $"{OutputFolder}/{id}.asset";

            var exist = AssetDatabase.LoadAssetAtPath<WeaponDefinitionSO>(assetPath);
            if (exist != null)
                continue;

            var so = ScriptableObject.CreateInstance<WeaponDefinitionSO>();
            so.weaponId = id;

            // 기본값(원하는 값으로 바꾸세요)
            so.baseDamage = 10;
            so.baseFireInterval = 0.6f;
            so.baseRange = 10f;
            so.targetPolicy = TargetPolicy.Nearest;
            so.avoidDuplicateTargets = true;

            AssetDatabase.CreateAsset(so, assetPath);
            created++;
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log($"[WeaponSoAutoGenerator] created={created}, folder={OutputFolder}");
    }

    private static void EnsureFolder(string folder)
    {
        if (AssetDatabase.IsValidFolder(folder))
            return;

        string[] parts = folder.Split('/');
        string current = parts[0];

        for (int i = 1; i < parts.Length; i++)
        {
            string next = current + "/" + parts[i];
            if (!AssetDatabase.IsValidFolder(next))
                AssetDatabase.CreateFolder(current, parts[i]);
            current = next;
        }
    }
}
#endif