#if UNITY_EDITOR
using System;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class PlayerSkillUpgradeMissingSOBootstrapper
{
    private const string OutFolder = "Assets/_Game/Scripts/So/SO_Weapon/_AutoGenerated";

    [MenuItem("Tools/그날이후/레벨업/누락 SO 자동 생성+연결(Deck/DB/Balance)")]
    public static void CreateAndWire()
    {
        EnsureFolder(OutFolder);

        // 1) 타입 찾기(프로젝트에 실제 클래스명이 다를 수 있어서 '이름 기반'으로 찾음)
        var deckType = FindTypeBySimpleName("WeaponSkillDeckSO");
        var dbType   = FindTypeBySimpleName("WeaponDatabaseSO");
        var balType  = FindTypeBySimpleName("UpgradeBalanceTableSO");

        if (deckType == null || dbType == null || balType == null)
        {
            Debug.LogError(
                "[레벨업] 타입을 못 찾음\n" +
                $"- WeaponSkillDeckSO: {(deckType!=null)}\n" +
                $"- WeaponDatabaseSO: {(dbType!=null)}\n" +
                $"- UpgradeBalanceTableSO: {(balType!=null)}\n" +
                "클래스명이 프로젝트에서 다른 경우, 실제 타입명을 알려주면 그걸로 맞춰줄게."
            );
            return;
        }

        // 2) 에셋 생성(이미 있으면 재사용)
        var deck = LoadOrCreateSO(deckType, $"{OutFolder}/WeaponSkillDeck_Auto.asset");
        var db   = LoadOrCreateSO(dbType,   $"{OutFolder}/WeaponDatabase_Auto.asset");
        var bal  = LoadOrCreateSO(balType,  $"{OutFolder}/UpgradeBalanceTable_Auto.asset");

        // 3) 씬에서 PlayerSkillUpgradeSystem 찾아서 연결
        var sys = UnityEngine.Object.FindFirstObjectByType<PlayerSkillUpgradeSystem>();
        if (sys == null)
        {
            Debug.LogWarning("[레벨업] 씬에서 PlayerSkillUpgradeSystem을 못 찾음. (씬 열고 다시 실행)");
            return;
        }

        var so = new SerializedObject(sys);
        SetObjectRef(so, "deck", db: deck); // deck 필드명이 다르면 아래 경고로 잡힘
        SetObjectRef(so, "weaponDatabase", db: db);
        SetObjectRef(so, "upgradeBalanceTable", db: bal);
        so.ApplyModifiedPropertiesWithoutUndo();
        EditorUtility.SetDirty(sys);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log("[레벨업] 누락 SO 생성+연결 완료. 이제 EMPTY가 아니라 카드가 나와야 정상.");
    }

    private static ScriptableObject LoadOrCreateSO(Type type, string path)
    {
        var asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(path);
        if (asset != null) return asset;

        asset = ScriptableObject.CreateInstance(type);
        AssetDatabase.CreateAsset(asset, path);
        EditorUtility.SetDirty(asset);
        Debug.Log($"[레벨업] 생성됨: {path}");
        return asset;
    }

    private static void SetObjectRef(SerializedObject so, string fieldName, ScriptableObject db)
    {
        var sp = so.FindProperty(fieldName);
        if (sp == null)
        {
            Debug.LogWarning($"[레벨업] 필드명을 못 찾음: {fieldName} (스크립트 실제 필드명 확인 필요)");
            return;
        }
        if (sp.propertyType != SerializedPropertyType.ObjectReference)
        {
            Debug.LogWarning($"[레벨업] 필드 타입이 ObjectReference가 아님: {fieldName}");
            return;
        }
        sp.objectReferenceValue = db;
    }

    private static Type FindTypeBySimpleName(string simpleName)
    {
        foreach (var asm in AppDomain.CurrentDomain.GetAssemblies())
        {
            Type[] types;
            try { types = asm.GetTypes(); }
            catch { continue; }

            foreach (var t in types)
            {
                if (t == null) continue;
                if (t.Name == simpleName) return t;
            }
        }
        return null;
    }

    private static void EnsureFolder(string folderPath)
    {
        if (AssetDatabase.IsValidFolder(folderPath)) return;

        string parent = Path.GetDirectoryName(folderPath)?.Replace("\\", "/");
        string name = Path.GetFileName(folderPath);

        if (!string.IsNullOrWhiteSpace(parent) && !AssetDatabase.IsValidFolder(parent))
            EnsureFolder(parent);

        if (!string.IsNullOrWhiteSpace(parent))
            AssetDatabase.CreateFolder(parent, name);
    }
}
#endif