// UTF-8
// 무기(슬롯 기반)용 SkillLevelTrackSO + WeaponSkillDeckSO 자동 생성 & Root_Skill에 자동 연결
// 목표: "덱 SO 못 찾음" + "Track SO None" 상태를 한 번에 끝냄

#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

public static class Tool_SkillRoot_WeaponTracksAndDeck_AutoGen
{
    // --------------------
    // 저장 경로(프로젝트 컨벤션에 맞춰 고정)
    // --------------------
    private const string ROOT_SKILL_DEFAULT_PATH = "Assets/_Game/Data/Roots/Root_Skill.asset";

    private const string AUTO_DIR_TRACKS = "Assets/_Game/Data/WS_TrackSO/_AutoGenerated";
    private const string AUTO_DIR_DECK   = "Assets/_Game/Data/WS_DeckSO/_AutoGenerated";
    private const string AUTO_DIR_TABLE  = "Assets/_Game/Data/WS_DeckSO/_AutoGenerated";

    private const string AUTO_DECK_NAME  = "WeaponSkillDeck_Auto";
    private const string AUTO_TABLE_NAME = "UpgradeBalanceTable_Auto";

    // --------------------
    // 메뉴
    // --------------------
    [MenuItem("Tool/그날이후/SO/스킬루트/무기 트랙+덱 자동 생성(프로토타입)")]
    public static void Generate()
    {
        // 0) Root_Skill 찾기(선택 우선, 없으면 기본 경로)
        var root = GetSelectedOrDefaultRootSkill();
        if (root == null)
        {
            Debug.LogError("[AutoGen] Root_Skill(SkillRootSO)을 찾지 못했습니다. Project에서 Root_Skill.asset을 선택한 뒤 다시 실행하세요.");
            return;
        }

        // 1) 폴더 보장
        EnsureFolder(AUTO_DIR_TRACKS);
        EnsureFolder(AUTO_DIR_DECK);
        EnsureFolder(AUTO_DIR_TABLE);

        // 2) 프로토타입 포함 무기 수집 (includeInPrototype=true 기준)
        var weaponDefs = FindPrototypeWeaponDefs();
        if (weaponDefs.Count == 0)
        {
            Debug.LogError("[AutoGen] includeInPrototype=true 인 WeaponDefinitionSO를 찾지 못했습니다. 무기 SO(WeaponDefinitionSO)부터 확인하세요.");
            return;
        }

        // 3) 밸런스 테이블 확보(없으면 자동 생성)
        var table = FindOrCreateBalanceTable();

        // 4) 덱 생성/갱신
        var deck = FindOrCreateDeckAsset();
        FillDeck(deck, weaponDefs);

        // 5) 트랙 생성/갱신
        var tracks = new List<SkillLevelTrackSO>(weaponDefs.Count);
        foreach (var w in weaponDefs)
        {
            var track = FindOrCreateTrackForWeapon(w);
            FillTrackSteps(track, w, table);
            tracks.Add(track);
        }

        // 6) Root_Skill에 트랙 연결(스크린샷의 Weapon Skill Tracks 리스트 채우기)
        ApplyTracksToRoot(root, tracks);

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log($"[AutoGen] 완료\n- Root: {AssetDatabase.GetAssetPath(root)}\n- Deck: {AssetDatabase.GetAssetPath(deck)}\n- Tracks: {tracks.Count}개 생성/갱신");
        EditorGUIUtility.PingObject(root);
        Selection.activeObject = root;
    }

    // --------------------
    // Root
    // --------------------
    private static SkillRootSO GetSelectedOrDefaultRootSkill()
    {
        // 선택 우선
        var sel = Selection.activeObject as SkillRootSO;
        if (sel != null) return sel;

        // 기본 경로
        return AssetDatabase.LoadAssetAtPath<SkillRootSO>(ROOT_SKILL_DEFAULT_PATH);
    }

    // --------------------
    // WeaponDefinitionSO 수집
    // --------------------
    private static List<WeaponDefinitionSO> FindPrototypeWeaponDefs()
    {
        var guids = AssetDatabase.FindAssets("t:WeaponDefinitionSO");
        var list = new List<WeaponDefinitionSO>(guids.Length);

        foreach (var g in guids)
        {
            var path = AssetDatabase.GUIDToAssetPath(g);
            var def = AssetDatabase.LoadAssetAtPath<WeaponDefinitionSO>(path);
            if (def == null) continue;

            // 프로토타입 포함 조건(기존 규칙 그대로)
            if (!def.includeInPrototype) continue;
            if (def.weight <= 0) continue;
            if (def.projectilePrefab == null) continue;
            if (string.IsNullOrWhiteSpace(def.weaponId)) continue;

            list.Add(def);
        }

        // weaponId 기준 정렬(덱/트랙 순서 안정화)
        list.Sort((a, b) => string.Compare(a.weaponId, b.weaponId, StringComparison.OrdinalIgnoreCase));
        return list;
    }

    // --------------------
    // Deck
    // --------------------
    private static WeaponSkillDeckSO FindOrCreateDeckAsset()
    {
        string path = $"{AUTO_DIR_DECK}/{AUTO_DECK_NAME}.asset";
        var deck = AssetDatabase.LoadAssetAtPath<WeaponSkillDeckSO>(path);
        if (deck != null) return deck;

        deck = ScriptableObject.CreateInstance<WeaponSkillDeckSO>();
        AssetDatabase.CreateAsset(deck, path);
        EditorUtility.SetDirty(deck);
        return deck;
    }

    private static void FillDeck(WeaponSkillDeckSO deck, List<WeaponDefinitionSO> defs)
    {
        // private List<WeaponDefinitionSO> weapons 필드에 SerializedObject로 주입
        var so = new SerializedObject(deck);
        var p = so.FindProperty("weapons");
        if (p == null || !p.isArray)
        {
            Debug.LogError("[AutoGen] WeaponSkillDeckSO 내부 필드(weapons)를 찾지 못했습니다. 필드명이 변경되었는지 확인하세요.");
            return;
        }

        p.arraySize = defs.Count;
        for (int i = 0; i < defs.Count; i++)
        {
            p.GetArrayElementAtIndex(i).objectReferenceValue = defs[i];
        }

        so.ApplyModifiedPropertiesWithoutUndo();
        EditorUtility.SetDirty(deck);
    }

    // --------------------
    // Track
    // --------------------
    private static SkillLevelTrackSO FindOrCreateTrackForWeapon(WeaponDefinitionSO weapon)
    {
        // 파일명은 weaponId 기반으로 고정(재실행 시 같은 에셋을 계속 갱신)
        string safe = SanitizeFileName(weapon.weaponId);
        string path = $"{AUTO_DIR_TRACKS}/SkillTrack_{safe}.asset";

        var track = AssetDatabase.LoadAssetAtPath<SkillLevelTrackSO>(path);
        if (track != null) return track;

        track = ScriptableObject.CreateInstance<SkillLevelTrackSO>();
        AssetDatabase.CreateAsset(track, path);
        EditorUtility.SetDirty(track);
        return track;
    }

    private static void FillTrackSteps(SkillLevelTrackSO track, WeaponDefinitionSO weapon, UpgradeBalanceTableSO table)
    {
        if (track == null || weapon == null) return;

        // 키/표시명 기본 세팅
        track.weaponId = weapon.weaponId;
        track.displayNameKr = string.IsNullOrWhiteSpace(weapon.displayNameKr) ? weapon.name : weapon.displayNameKr;

        // steps 8개 보장
        if (track.steps == null) track.steps = new List<SkillLevelTrackSO.LevelStep>(8);
        EnsureListSize(track.steps, 8, () => new SkillLevelTrackSO.LevelStep());

        // 각 레벨의 upgrades 최소 1개는 넣어둔다(카드 후보가 0이면 아무 것도 안 뜸)
        // 안전 기본값(프로토타입용):
        // Lv1: ToggleEnabled(활성화)
        // Lv2: DamageAdd
        // Lv3: CooldownMul
        // Lv4: RangeAdd
        // Lv5: DamageAdd
        // Lv6: CooldownMul
        // Lv7: RangeAdd
        // Lv8: DamageAdd
        for (int lv = 1; lv <= 8; lv++)
        {
            var step = track.steps[lv - 1];
            if (step == null)
            {
                step = new SkillLevelTrackSO.LevelStep();
                track.steps[lv - 1] = step;
            }

            if (step.upgrades == null) step.upgrades = new List<SkillLevelTrackSO.UpgradeDef>(1);

            // 기존 값이 이미 있으면 덮어쓰기(자동생성 기준)
            step.upgrades.Clear();

            var u = new SkillLevelTrackSO.UpgradeDef();
            u.tagsKr = string.IsNullOrWhiteSpace(weapon.tagsKr) ? "공통" : weapon.tagsKr;

            if (lv == 1)
            {
                u.type = WeaponUpgradeType.ToggleEnabled;
                u.value = UpgradeValue.Toggle(true);
                u.titleOverrideKr = $"{track.GetDisplayName()} 활성화";
            }
            else
            {
                // 밸런스 테이블 값을 무기 성장 성향(스케일)로 보정해서 넣는다.
                // DamageAdd/RangeAdd = 곱연산
                // CooldownMul = 지수 보정(0.95^scale)
                int dmgAdd = Mathf.RoundToInt(table.GetDamageAdd(lv) * weapon.damageStepScale);
                float rangeAdd = table.GetRangeAdd(lv) * weapon.rangeStepScale;

                float baseMul = table.GetCooldownMul(lv);
                float cdMul = Mathf.Pow(baseMul, Mathf.Max(0.0001f, weapon.cooldownStepScale));

                // 순환 패턴
                int mod = lv % 3; // 2->Damage, 0->Cooldown, 1->Range (lv=2 mod=2)
                if (lv == 8) mod = 2; // 마지막은 Damage로 고정

                if (mod == 2)
                {
                    u.type = WeaponUpgradeType.DamageAdd;
                    u.value = UpgradeValue.AddInt(Mathf.Max(1, dmgAdd));
                    u.titleOverrideKr = ""; // 빌더에서 자동 생성되게 둠
                }
                else if (mod == 0)
                {
                    u.type = WeaponUpgradeType.CooldownMul;
                    // 0이나 1 이상이 나오면 이상하니 안전장치
                    u.value = UpgradeValue.MulFloat(Mathf.Clamp(cdMul, 0.05f, 2.0f));
                    u.titleOverrideKr = "";
                }
                else
                {
                    u.type = WeaponUpgradeType.RangeAdd;
                    u.value = UpgradeValue.AddFloat(Mathf.Max(0.1f, rangeAdd));
                    u.titleOverrideKr = "";
                }
            }

            step.upgrades.Add(u);
        }

        EditorUtility.SetDirty(track);
    }

    // --------------------
    // Root 적용
    // --------------------
    private static void ApplyTracksToRoot(SkillRootSO root, List<SkillLevelTrackSO> tracks)
    {
        if (root.weaponSkillTracks == null)
            root.weaponSkillTracks = new List<SkillLevelTrackSO>(tracks.Count);

        root.weaponSkillTracks.Clear();
        root.weaponSkillTracks.AddRange(tracks);

        EditorUtility.SetDirty(root);
    }

    // --------------------
    // Balance Table
    // --------------------
    private static UpgradeBalanceTableSO FindOrCreateBalanceTable()
    {
        // 1) 프로젝트 내 아무 UpgradeBalanceTableSO나 있으면 그걸 사용(첫 번째)
        var guid = AssetDatabase.FindAssets("t:UpgradeBalanceTableSO").FirstOrDefault();
        if (!string.IsNullOrEmpty(guid))
        {
            var path = AssetDatabase.GUIDToAssetPath(guid);
            var existing = AssetDatabase.LoadAssetAtPath<UpgradeBalanceTableSO>(path);
            if (existing != null) return existing;
        }

        // 2) 없으면 자동 생성
        string pathAuto = $"{AUTO_DIR_TABLE}/{AUTO_TABLE_NAME}.asset";
        var auto = AssetDatabase.LoadAssetAtPath<UpgradeBalanceTableSO>(pathAuto);
        if (auto != null) return auto;

        auto = ScriptableObject.CreateInstance<UpgradeBalanceTableSO>();
        AssetDatabase.CreateAsset(auto, pathAuto);
        EditorUtility.SetDirty(auto);

        // 자동 생성된 테이블은 기본값으로 두고(스크립트 OnValidate가 채움),
        // 사용자가 나중에 값 조정하면 전체 무기 트랙에 반영 가능.
        return auto;
    }

    // --------------------
    // Utils
    // --------------------
    private static void EnsureFolder(string fullAssetPath)
    {
        // 예: Assets/_Game/Data/WS_TrackSO/_AutoGenerated
        if (AssetDatabase.IsValidFolder(fullAssetPath)) return;

        var parts = fullAssetPath.Split('/');
        string cur = parts[0]; // "Assets"
        for (int i = 1; i < parts.Length; i++)
        {
            string next = cur + "/" + parts[i];
            if (!AssetDatabase.IsValidFolder(next))
            {
                AssetDatabase.CreateFolder(cur, parts[i]);
            }
            cur = next;
        }
    }

    private static void EnsureListSize<T>(List<T> list, int size, Func<T> factory) where T : class
    {
        while (list.Count < size) list.Add(factory());
        while (list.Count > size) list.RemoveAt(list.Count - 1);
    }

    private static string SanitizeFileName(string s)
    {
        if (string.IsNullOrWhiteSpace(s)) return "Unknown";
        foreach (var c in Path.GetInvalidFileNameChars())
            s = s.Replace(c, '_');
        return s;
    }
}
#endif